version: '3'
services:
  helloapp:
    container_name: helloapp
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'

volumes:
  mongo_data: